### ISSUE TITLE
Coq 8.12 release?

### ISSUE THREAD

**Issue by anton-trunov** [damien-pous/relation-algebra#14]
Looks like neither `v1.7.3` tag, nor the current `master` branch are compatible with Coq 8.12.

**Comment by chdoc** [comment]
I just had a look at the [lists of commits](https://github.com/damien-pous/relation-algebra/commits/master). I would expect/hope that `c3c669003d9b3f1d0b2f97a197f81b8efd80f5b7` compiles with 8.12 and suspect that the subsequent commit no longer does. But you probably know better than me which of those coq PRs made it into 8.12 and which didn't. @anton-trunov , can you confirm this?

Pinging @damien-pous so that he can maybe craft a release.

**Comment by anton-trunov** [comment]
@chdoc Yes, you are right c3c669003d9b3f1d0b2f97a197f81b8efd80f5b7 compiles just fine with Coq 8.12. Thanks!

**Comment by damien-pous** [comment]
I've just released a v1.7.4 which is compatible with both 8.11 and 8.12. 
Waiting for the opam CI to confirm that everything is fine.
Thanks for spotting this @anton-trunov !

**Comment by anton-trunov** [comment]
@damien-pous Great! Thanks for fixing that. (Kudos to @volodeyka who actually made me aware of this issue)
