### ISSUE TITLE
status of example files in the library

### ISSUE THREAD

**Issue by damien-pous** [damien-pous/relation-algebra#33]
@damien-pous : a note on our "smoke test kit" (a quick check Coq Platform does to check if all packages are installed properly): I selected the files `compiler_opts.v` and `imp.v` for smoke testing which appear to be examples and coqc reasonably fast. I would appreciate if in a future release you could change these files such that they use `From RelationAlgebra Require ...` to require modules from you package (you can link this to . in your _CoqProject file). As is I need to patch the files for smoke testing. This would be also useful for users trying your examples, because as is they won't run with an opam installed coq-relation-algebra.

_Originally posted by @MSoegtropIMC in https://github.com/coq/platform/issues/167#issuecomment-1077349995_

**Comment by damien-pous** [comment]
Hi @MSoegtropIMC,  
(Reopening the issue here for the record, and to follow-up)

I can do that, sure. Can you be more explicit about what I should do in the _CoqProject file ?

In fact this is a question I wanted to ask somewhere : I tend to have both test files and example files in my libraries, and I don't know how I'm supposed to package them. When those files are long to compile (sometimes on purpose), I'd be happy to compile them from time to time, but not to require every user to do so. I can imagine tricks to do that, but maybe there is a standard way?

Best,
Damien

**Comment by MSoegtropIMC** [comment]
> I can do that, sure. Can you be more explicit about what I should do in the _CoqProject file ?

If you compile locally, you need to tell coqc that the Coq logical path "RelationAlgebra" is your root folder - otherwise the example files won't compile any more. So what is needed in _CoqProject is (I guess) something like `-Q . RelationAlgebra` and then use `From RelationalAlgebra` for all Requires of files of your package.

Quite a few package providers also use the installed logical path in the library files - not just the examples, so that uses can open and run a library file in an IDE to better understand it without recompiling your complete package from sources.

I can't say much about separating test/example files in auto genrated Coq makefiles - most package maintainers for projects where this is required use manually create makefiles - or recently dune.

But I think in your case things are fine as is - the examples all together compile in <30s if I remember right. No need to get fancy to save that IMHO.

Btw.: it would make sense to have a few subfolders, say `src` for OCaml, `theories` for Coq and examples for examples. Especially the last one is important, because this is what users look at first and they might get frustrated if they can't find the examples.

**Comment by damien-pous** [comment]
Hi again @MSoegtropIMC,
I did reorganise the files as proposed above in the v1.7.8 release: now the three examples are in folder examples/ and use the "From RelationAlgebra Require Import ..." syntax.
I close the issue, please reopen if this is not yet ok...
